version: '2.23'

networks:
  network:
    driver: bridge

services:
  catalog.api:
    build:
      context: .
      dockerfile: Catalog/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - network
      
  nginx:
    image: nginx
    container_name: ide.nginx
    ports:
      - "80:80"
    networks:
      - network
