version: '3'

networks:
  sss:
    driver: bridge

services:
  sqlserv:
    container_name: db
    networks:
        - sss
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "MyPassword123!"
    ports:
    - "1401:1433"


  optimistic_kalam:
    container_name: app
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    networks:
        - sss  
    image: webapi
    ports:
        - "8080:80" 
    depends_on: 
        - sqlserv
    build:
        context: .
        dockerfile: Dockerfile

